version: '3.3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=thomas
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=safetynet

networks:
  all:
    driver: bridge